"""Tests for Undertow GitHub PR comment Markdown reporter."""

from datetime import UTC, datetime

from undertow.models import (
    AttributionHop,
    AttributionPath,
    Finding,
    FindingKind,
    RuledFinding,
    Severity,
    Verdict,
)
from undertow.reporter.github import PROJECT_URL, format_github_comment


def test_format_github_comment_block() -> None:
    model_urn = "urn:li:mlModel:(urn:li:dataPlatform:mlflow,fraud_detector_v3,PROD)"
    ds_urn = "urn:li:dataset:(urn:li:dataPlatform:snowflake,staging.payments_clean,PROD)"
    feat_urn = "urn:li:mlFeature:(txn_aggregates,avg_txn_30d)"

    path = AttributionPath(
        hops=(
            AttributionHop(urn=ds_urn, entity_type="dataset", column="amount_usd"),
            AttributionHop(urn=feat_urn, entity_type="mlFeature", via="DerivedFrom"),
            AttributionHop(urn=model_urn, entity_type="mlModel", via="Consumes"),
        ),
        owners=("data-eng-tom",),
    )

    finding = Finding(
        kind=FindingKind.COLUMN_DROPPED,
        subject_urn=ds_urn,
        subject_column="amount_usd",
        affected_feature_urn=feat_urn,
        summary="Column amount_usd was dropped from upstream table",
        path=path,
    )

    ruled = RuledFinding(
        finding=finding,
        severity=Severity.BLOCK,
        rule_id="upstream-column-dropped",
    )

    verdict = Verdict(
        model_urn=model_urn,
        severity=Severity.BLOCK,
        ruled_findings=(ruled,),
        assets_checked=10,
        checked_at=datetime.now(UTC),
    )

    narrative = "Custom narrative summary explaining why this PR is blocked."
    output = format_github_comment(verdict, narrative=narrative)

    assert "## 🔴 Undertow ML Gate: BLOCKED" in output
    assert f"`{model_urn}`" in output
    assert "Narrative Summary" in output
    assert narrative in output
    assert "Blocking Findings" in output
    assert "COLUMN_DROPPED" in output
    assert "data-eng-tom" in output
    # The footer link lands in every PR comment Undertow writes, so it has to
    # point at a repository that exists. It previously pointed at a 404.
    assert f"({PROJECT_URL})" in output
    assert PROJECT_URL.startswith("https://github.com/")


def test_format_github_comment_clear() -> None:
    model_urn = "urn:li:mlModel:(urn:li:dataPlatform:mlflow,fraud_detector_v3,PROD)"

    verdict = Verdict(
        model_urn=model_urn,
        severity=Severity.CLEAR,
        ruled_findings=(),
        assets_checked=8,
        checked_at=datetime.now(UTC),
    )

    output = format_github_comment(verdict)

    assert "## 🟢 Undertow ML Gate: CLEARED" in output
    assert f"`{model_urn}`" in output
    assert "Generated by [Undertow]" in output
