"""GitHub PR comment markdown formatter for Undertow verdicts."""

from __future__ import annotations

from undertow.models import Severity, Verdict

PROJECT_URL = "https://github.com/danielamodu/Undertow"


def format_github_comment(verdict: Verdict, narrative: str | None = None) -> str:
    """Format a Verdict (and optional narrative) as a GitHub Markdown PR comment."""
    emoji = (
        "🔴"
        if verdict.severity is Severity.BLOCK
        else ("🟡" if verdict.severity is Severity.WARN else "🟢")
    )
    status_title = (
        "BLOCKED"
        if verdict.severity is Severity.BLOCK
        else ("WARNED" if verdict.severity is Severity.WARN else "CLEARED")
    )

    lines: list[str] = [
        f"## {emoji} Undertow ML Gate: {status_title}",
        "",
        f"**Model URN:** `{verdict.model_urn}`",
        f"**Assets Checked:** {verdict.assets_checked} | "
        f"**Checked At:** {verdict.checked_at.isoformat()}",
        "",
    ]

    if narrative:
        lines.extend(["### Narrative Summary", "", narrative, ""])

    if verdict.blocking:
        lines.extend([f"### 🔴 Blocking Findings ({len(verdict.blocking)})", ""])
        for rf in verdict.blocking:
            finding = rf.finding
            subj = finding.subject_column or finding.subject_urn
            feat = finding.affected_feature_urn or "N/A"
            owners = (
                ", ".join(finding.path.owners)
                if finding.path and finding.path.owners
                else "Unassigned"
            )

            lines.append(f"#### ❌ `{finding.kind.value}` on `{subj}`")
            lines.append(f"- **Summary:** {finding.summary}")
            lines.append(f"- **Affected Feature:** `{feat}`")
            lines.append(f"- **Confidence:** `{finding.confidence.value}`")
            lines.append(f"- **Owners:** {owners}")

            if finding.path and finding.path.hops:
                lines.append("- **Attribution Path:**")
                path_str = " ➔ ".join(f"`{h.label()}`" for h in finding.path.hops)
                lines.append(f"  {path_str}")

            if rf.exempted_by:
                lines.append(
                    f"- **Exemption Note:** {rf.exempted_by} "
                    f"(expires {rf.exemption_expires})"
                )
            lines.append("")

    if verdict.warnings:
        lines.extend([f"### 🟡 Warning Findings ({len(verdict.warnings)})", ""])
        for rf in verdict.warnings:
            finding = rf.finding
            subj = finding.subject_column or finding.subject_urn
            feat = finding.affected_feature_urn or "N/A"
            owners = (
                ", ".join(finding.path.owners)
                if finding.path and finding.path.owners
                else "Unassigned"
            )

            lines.append(f"#### ⚠️ `{finding.kind.value}` on `{subj}`")
            lines.append(f"- **Summary:** {finding.summary}")
            lines.append(f"- **Affected Feature:** `{feat}`")
            lines.append(f"- **Confidence:** `{finding.confidence.value}`")
            lines.append(f"- **Owners:** {owners}")

            if finding.path and finding.path.hops:
                lines.append("- **Attribution Path:**")
                path_str = " ➔ ".join(f"`{h.label()}`" for h in finding.path.hops)
                lines.append(f"  {path_str}")
            lines.append("")

    lines.extend(
        [
            "---",
            f"*Generated by [Undertow]({PROJECT_URL}) — lineage-grounded ML deploy gate*",
        ]
    )

    return "\n".join(lines)
